# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e079037c6f6ad21c780dcc40e0c36cc9502d459c82fd998bd8be60add0429dcbd756e12f60a0211dea80555b2b4b5e228d6577ebad406d17ad85c070a6f043

test:
  secret_key_base: 78d67636251428689eb1ad8504657b1f6d70c9257c1a5fc5dc36312d06bbd7c365949bbc6894423d1ebfb2a480981113f05fa1c542fdde55da5390f4c4796f85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
